### ISSUE TITLE
This really does not seem to work reliably.

### ISSUE THREAD

**Issue by MagnumDopus** [nicksardo/GoTime#1]
I have created a webapp that syncs a progressive minute count across browsers, that application can be found here:  https://timer-magnumdopus.c9users.io/

I have posted my code in this jsfiddle for my client side javascript and my html: https://jsfiddle.net/r9q2a14n/

Its a relatively simple app.  I am only using websockets,  using socket.io on my node server and on the client.  After GoTime syncs ten times I check to see if its precision is <40ms.  If it is I consider the app synchronized.  I then display the Achieved GoTime and allow users to set an alarm that syncs across all browsers using the websocket.  

Assuming GoTime is operating correctly, with a precision of 40ms or less, the greatest discrepency between the alarms sounding should be 85 ms (Assuming a -40ms offset, a +40ms offset, and the setInterval duration being 5ms).  

However that is not the case.  Despite the fact that the browser is considered snyced after a precision of <40 is achieved, the alarms will still sound almost 800ms apart.  This is really bizarre and makes the app completely worthless. 

To reproduce just open a bunch of tabs of my app above, wait for them all to sync, then set a timer in one.  They will all alarm at different times.  

I am scratching my head over this but it would appear this library is not reliable.

**Comment by nicksardo** [comment]
This library is 150 lines of code and doesn't have much room for error. I've never seen it stray other than due to network latency (low precision).  Otherwise, it syncs up fine for me on multiple tabs, browsers, devices, and even on mobile. 

If you don't think the library is reliable, you're welcome to make your own.

**Comment by MagnumDopus** [comment]
I think its a really great library, I like what its trying to accomplish, but I cannot seem to get it to do what I expected it to do.  It is certainly possible I am doing something stupid or wrong, it would hardly be the first time, so if something is obviously wrong I'd love to know.  Otherwise I would be only raising this issue so others might not stray down the path to find an unreliable solution awaiting them.  And if I am wrong, than it will prove to be even more useful to the people who could make similar mistakes!

**Comment by MagnumDopus** [comment]
If the library is doing what you claim it to do, and reliably so, then please help me understand why my solution using the library doesn't work.  I have provided you with ways to reproduce easily, and I am relying on low precision (<40ms) for this to operate.

**Comment by MagnumDopus** [comment]
After doing lots of testing on chronograph.io it seems like they manage to get near-instant syncronization, something I am not getting and something I am still scratching my head about.  So it would seem the library is probably perfectly reliable just my implementation is somehow bogged.
