### ISSUE TITLE
Inaccurate calculation of offset

### ISSUE THREAD

**Issue by colonelchlorine** [nicksardo/GoTime#2]
When reviewing the calculations of your `offset` and then the correction in the `now` method, I find there are some inaccuracies. Basing this on the example timing Wikipedia's article on [NTP](https://en.wikipedia.org/wiki/Network_Time_Protocol).

![NTP](https://upload.wikimedia.org/wikipedia/commons/8/8d/NTP-Algorithm.svg)

Mapping of your variables when using XHR to the image's:
```
t0 = requestTime
t1 = serverTime
t2 = serverTime
t3 = responseTime
```
Calculation of offset in `_calculateOffset`:
```
offset = t1 - t0 + ((t3 - t0) / 2)
       = 135 - 231 + ((298 - 231) / 2)
       = -62.5
```

Calculation of server time at 231 in `now`:
```
serverNow = 231 + -(62.5)
          = 168.5
```

Am I missing something from your algorithm? The expected value should be around 101ms (33.5ms earlier, which is estimated at half the round-trip-time).

I suggest you should be **subtracting** the `oneway` time from the difference in the `_calculateOffset` function:

```
  @_calculateOffset: (requestTime, responseTime, serverTime) ->
    duration = responseTime - requestTime
    oneway = duration / 2
    return {
      offset: serverTime - requestTime - oneway
      precision: oneway
    }
```

Thoughts?

p.s. Glad to see this repo out there. Very strong response to a lot of the SO questions on this topic. Websockets too, very nice.

**Comment by nicksardo** [comment]
Nice catch! Can't believe anyone looks at this repo anymore.

**Comment by colonelchlorine** [comment]
Good stuff! Fastest fix I've seen on Github :)

The JS compiled code looks very slick now too.
